version: '3'
services:

  gitea: 
    image: "gitea/gitea"
    container_name: "gitea" 
    environment: 
      - USER_UID=1000 
      - USER_GID=1000 
      - SSH_PORT=222
      - HTTP_PORT=80
      - ROOT_URL=http://${HOST_IP_ADDRESS}
      - DOMAIN=${HOST_IP_ADDRESS}
    restart: always 
    volumes: 
      - ./gitea-data:/data 
      - /etc/timezone:/etc/timezone:ro 
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - "80:80"
      - "222:222"

  drone:
    image: 'drone/drone:2'
    container_name: drone
    restart: unless-stopped
    ports:
      - '82:80'
      - '81:81'
    environment:
       - DRONE_GITEA_SERVER=http://${HOST_IP_ADDRESS}
       - DRONE_GITEA_CLIENT_ID=<put your client id here>
       - DRONE_GITEA_CLIENT_SECRET=<put your secret here>
       - DRONE_RPC_SECRET=<put-a-random-string-or-bash-your-keyboard>
       - DRONE_SERVER_HOST=${HOST_IP_ADDRESS}:81
       - DRONE_SERVER_PORT=:81
       - DRONE_HOST=http://${HOST_IP_ADDRESS}:81
       - DRONE_SERVER_PROTO=http
       - DRONE_CLEANUP_DEADLINE_PENDING=15m
       - DRONE_CLEANUP_INTERVAL=15m
       - DRONE_CLEANUP_DEADLINE_RUNNING=15m
    volumes:
      - ./data/drone:/data

  drone-runner:
    image: 'drone/drone-runner-docker:1'
    container_name: drone-runner
    restart: unless-stopped
    environment:
       - DRONE_RPC_HOST=drone:81
       - DRONE_RPC_PROTO=http
       - DRONE_RPC_SECRET=<put-a-random-string-or-bash-your-keyboard>
       - DRONE_RUNNER_CAPACITY=10
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
       - drone

